### ISSUE TITLE
Fix links in WordPress

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/container#13]
Currently, the links in wordpress for the Java applications look like this: http://localhost:8080/PathwayBrowser but this will not work because Tomcat is listening on 8082: http://localhost:8082/PathwayBrowser 

We need to make sure that the links in WordPress still point to the Java applications correctly.

Possible solutions:
1. Change the database. This means writing a script to change all links to the applications to point *explicitly* to localhost:8082. 
2. Some sort of internal redirect within WordPress. This might be possible with an Apache configuration, maybe a rewrite rule?
3. ???

**Comment by AyushyaChitransh** [comment]
Fixed in commit adeeefc

**Comment by SolomonShorser-OICR** [comment]
It will probably be necessary to add RewriteRules for other web applications.
