### ISSUE TITLE
Capture log files

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/container#29]
We need to be able to capture log files for:

 - neo4j
 -  solr
 - mysql
 -  apache tomcat
 - apache server for WordPress.

There is already a directory where log files for tomcat, and the Java applications that run in Tomcat. Logs for these other applications can to be saved in the same "logs" directory.

**Comment by AyushyaChitransh** [comment]
Volume Specification for capturing logs:

- neo4j-db:
`- ./logs/neo4j/:/var/lib/neo4j/logs/`

- solr: 
`- ./logs/solr/:/opt/solr/server/logs/`

- apache tomcat: Done previously.

- apache server for wordpress: 
`- ./logs/apache/:/var/log/apache2`

- mysql: 
`- ./logs/mysql-for-wordpress/:/var/log/mysql/` This log is at error level only. We can change it by modifying `/etc/mysql/conf.d/mysql.cnf`. 


Logs captured: neo4j-db, solr, apache for wordpress, apache tomcat
Currently working on: Mysql logs. It is not working yet, am looking into it. Probably permission issues.

**Comment by AyushyaChitransh** [comment]
Commit 7a42c15f06b1796f87093e5823c548ccf76c5bec captures logs of neo4j-db, solr, apache-worspress.

Commit 23a034903b9330567d55d230eaec3bcdfbe4dc0 modifies permissions of solr log directory. 

Mysql logs are yet to be captured.

**Comment by AyushyaChitransh** [comment]
### Problem

Mysql from container is unable to access logdir. 

### Context

Mysql logs can be written by `mysql` user from inside the container. And that user requires ownership of the directory in which logs are stored. 

### Possible fix

From [docker-library/mysql](https://github.com/docker-library/mysql/issues/146):
With `container` as working directory, and using `chown -R 999:999 ./logs/mysql` to change ownership, this ownership problem can be solved. After changing ownership, please verify if ownership has changed or not. You can use: `stat ./logs/mysql`.

If you are unable to change ownership, refer to [Ownership remains unchanged after `sudo chown` in ubuntu](https://superuser.com/q/1237368/396312) and [How do I correctly mount a NTFS partition in /etc/fstab?](https://askubuntu.com/q/113733/353904)

### Solution

[deploy.sh](https://github.com/reactome/container/blob/develop/deploy.sh) will create required directory and then run `chown -R 999:999 ./logs/mysql` before starting the containers.

**Comment by AyushyaChitransh** [comment]
Previous solution might not be as portable as docker containers should be. We require `chown` but that seems to fail for NTFS file-systems mounted inside linux.

### Alternate solution

We can use internal volumes of docker, and perform chown there. And provide a link to log file in the our desired location.

**Comment by AyushyaChitransh** [comment]
###  In case `chown` fails to change the ownership

The logs will get stored in internal directory of docker. A link to internal directory of docker is provided in `logs/mysql` folder.Viewing that directory may require sudo permissions. In case user is unable to view the internal directory, a copy of logs from previous run of container is also getting stored in `logs/mysql/tomcat/backup` and `logs/mysql/wordpress/backup`

Commit 483aa42f0796962c85a6cd08a0cd4cd08d68cc67

**Comment by AyushyaChitransh** [comment]
###  In case `chown` fails to change the ownership

The logs will get stored in internal directory of docker. A link to internal directory of docker will be provided in `logs/mysql` folder by `deploy.sh` script. Viewing that internal directory may require `sudo` permissions. 

In case user is unable to view the internal directory, a copy of logs from previous run of container is also getting stored in `logs/mysql/tomcat/backup` and `logs/mysql/wordpress/backup`

Commit 483aa42f0796962c85a6cd08a0cd4cd08d68cc67
