### ISSUE TITLE
Search function does not quite work.

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/container#33]
The search function does not quite work. You can type in the search field and you can see the auto-complete suggestions coming back from solr, and the solr log and tomcat log suggest that things are working, but if you actually try to go to a search result page, you end up on the "results not found - contact us" page.

**Comment by SolomonShorser-OICR** [comment]
This might be a version tomcat issue. In the tomcat localhost file, I was seeing this message when running a search:

```
15-Aug-2017 18:49:17.576 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [mvc-dispatcher] in context with path [/content] threw exception [Invalid tld file: [/WEB-INF/tags/customTag.tld], see JSP specification section 7.3.1 for more details] with root cause
 org.apache.jasper.JasperException: Invalid tld file: [/WEB-INF/tags/customTag.tld], see JSP specification section 7.3.1 for more details
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:294)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:81)
        at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:281)
        at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:122)
...
[SNIPPED LONG STACK TRACE]
```

Some searching online for the message "Invalid tld file see JSP specification section 7.3.1" brought back search hits that suggested that the same application that worked fine in older versions of tomcat would have this error in newer versions of tomcat. I found a [stackoverflow post](https://stackoverflow.com/a/39264879) that clarifies the error. 

I followed the advice and renamed customTag.tld to implicit.tld and then updated the files that referenced customTag.tld. Then I restarted the application and the search function worked fine! Unfortunately, I couldn't find a docker image of the tomcat version used on the server, so we'll probably need to update the application.

**Comment by AyushyaChitransh** [comment]
Updating application seems a better idea. Since using older version of tomcat image would require us to write rewrite rules manually, which was the main reason we switched to tomcat:8

**Comment by SolomonShorser-OICR** [comment]
A fix to this can be seen here: 
https://github.com/reactome/container/blob/e71f6894e86da56b804b13fb9513feab02fff9ab/java-application-builder/maven_builds.sh#L69-L76
