### ISSUE TITLE
Flags in deploy script

### ISSUE THREAD

**Issue by AyushyaChitransh** [reactome/container#35]
While deploying I was thinking to provide users with some options. Users may run the deploy script with some of these flags or use multiple flags while running the script. If no flag is used, the default behavior will be to run the the containers. The flags I am talking about are as follows:

  -  `-u` to Update database files. This will not update those files which can be built locally. Example: analysis.bin, interactors.db. The files that will be updated include: database files, diagrams and fireworks, solr_data.

 -  `-u all` to Update all files. This will include all big files. If the files are not present, then they will be downloaded and if they are present and not consistent with the current remote version then they will be updated.

 - `-d` to Download database files. This flag will remove old database files (if present) and download new files from remote server. Similar to update flag, this will not include those files which can be built locally. And will download only those files as described in Update flag.

 - `-d all` to Download all files. This flag will remove previous files and download new ones. The files that will be affected include: database files, diagrams and fireworks, solr_data. And due to all argument, it will also include: analysis.bin, interactors.db.

 - `-b`  is Build flag. Rebuild essential war files.
 
 - `-b all` is Build all flag. It will build all webapps. Data files like analysis.bin and interactors.db will also be built due to the presence of all argument.

 - `-b select` It will allow user to select which webapps to build. By using this flag, the user will be presented with name of the services and from there user will be required to press y/n for yes/no if the service should be built or not.

**Comment by AyushyaChitransh** [comment]
A more complete version of usage message is mentioned [here](https://github.com/reactome/container/commit/85bbf64c25d5088c38cf3f5278e51c7970db9d47#diff-60254338249f657a0a83f98258a56bfeR294) in commit 85bbf64c25d5088c38cf3f5278e51c7970db9d47

**Comment by SolomonShorser-OICR** [comment]
See: https://github.com/reactome/container/pull/40
