### ISSUE TITLE
Data/archives (analysis_v61.bin.gz) not found

### ISSUE THREAD

**Issue by shkao** [reactome/container#48]
Hello,

I'm calling `deploy.sh` but it seems the file is no longer there?

```
bash deploy.sh -d all -b all -r                                                                                                                                   
Selected 'all'. All previous archives, if present, will be deleted and new ones will be downloaded.
#######################################################################
# Filename:   analysis.bin.gz
#######################################################################
Old file deleted, downloading new one...
--2018-04-16 15:46:01--  https://reactome.org/download/current/analysis_v61.bin.gz
Resolving reactome.org (reactome.org)... 206.108.125.163
Connecting to reactome.org (reactome.org)|206.108.125.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-16 15:46:02 ERROR 404: Not Found.
```

Search around https://reactome.org/download/current/ but I still couldn't find an updated one, can you update the URL? Thanks in advance.

**Comment by SolomonShorser-OICR** [comment]
Hi @shkao,
This project is currently a work-in-progress. It is undergoing an internal reorganization, after the Reactome site switched from WordPress to Joomla. The way we handle the data files has changed, and as a result, this analysis file is not currently available in the download directory. I'm sorry if this has caused you any problems. If you have any further questions or concerns, you can email them to the Reactome Help mailing list at  help@reactome.org
Thanks,
Solomon Shorser.

**Comment by shkao** [comment]
I see, thanks for getting me back.

**Comment by SolomonShorser-OICR** [comment]
Hi @shkao,
Currently, we do not have a simple method for installing a local Reactome instance. Most of the Reactome data sources are available for [download](https://reactome.org/download-data). The graph database (for Neo4J) is here: https://reactome.org/download/current/reactome.graphdb.tgz and the relational database (for MySQL)  is here: https://reactome.org/download/current/databases/gk_current.sql.gz

Many users download these databases to do their own local queries and analysis.

Reactome also provides a  number of web services that can be accessed from your own program. More information can be found in the [Developer's Zone](https://reactome.org/dev).

Do these services provide the functionality you need?

**Comment by shkao** [comment]
Yes, thanks a lot @SolomonShorser-OICR !
