### ISSUE TITLE
build CuratorTool from maven_buils.sh

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/container#7]
maven_builds.sh will need to be updated to call the new ant build task to compile the Java source of CuratorTool. This needs to be done as a precursor to building "reactome.jar".

**Comment by SolomonShorser-OICR** [comment]
This issue: https://github.com/reactome/container/issues/8 needs to be completed before *this* issue can be completed.

**Comment by AyushyaChitransh** [comment]
In building CreatorTool, do we want to build jar files from all `.xml` files present in ANT folder of curator tool?

**Comment by AyushyaChitransh** [comment]
Target named `bundleapp` has not been included as it was a MacOS X application, and I needed to confirm if it is to be included or not. If it is not required then commit 30301fb5f655de2f8a9d3cd125f439b93b9b12f8 closes this issue.

**Comment by SolomonShorser-OICR** [comment]
I don't think that `bundleapp` is necessary right now. We don't need to run CuratorTool on OS X, we need to compile enough of CuratorTool so that we can build reactome.jar and since it looks like reactome.jar now builds OK, I'm going to close this issue.
